# -*- coding: ISO-8859-1 -*-
"""Resource logo_svg (from file logo.svg)"""
# written by resourcepackage: (1, 0, 1)
source = 'logo.svg'
package = 'smashlib.resources'
data = (b'<?xml version="1.0" encoding="UTF-8" standalone="no"?>\n<!-- '
+b'Created with Inkscape (http://www.inkscape.org/) -->\n<svg\n  '
+b' xmlns:dc="http://purl.org/dc/elements/1.1/"\n   xmlns:cc="ht'
+b'tp://web.resource.org/cc/"\n   xmlns:rdf="http://www.w3.org/1'
+b'999/02/22-rdf-syntax-ns#"\n   xmlns:svg="http://www.w3.org/20'
+b'00/svg"\n   xmlns="http://www.w3.org/2000/svg"\n   xmlns:sodip'
+b'odi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd"\n   '
+b'xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"'
+b'\n   width="300"\n   height="300"\n   id="svg2"\n   sodipodi:ver'
+b'sion="0.32"\n   inkscape:version="0.44.1"\n   version="1.0"\n  '
+b' sodipodi:docbase="/home/vijaykumar/projects/smash/icons"\n  '
+b' sodipodi:docname="logo.svg"\n   inkscape:export-filename="/h'
+b'ome/vijaykumar/projects/smash/icons/logo-128.png"\n   inkscap'
+b'e:export-xdpi="38.400002"\n   inkscape:export-ydpi="38.400002'
+b'">\n  <defs\n     id="defs4" />\n  <sodipodi:namedview\n     id='
+b'"base"\n     pagecolor="#ffffff"\n     bordercolor="#666666"\n '
+b'    borderopacity="1.0"\n     gridtolerance="10000"\n     guid'
+b'etolerance="10"\n     objecttolerance="10"\n     inkscape:page'
+b'opacity="0.0"\n     inkscape:pageshadow="2"\n     inkscape:zoo'
+b'm="1"\n     inkscape:cx="414.59685"\n     inkscape:cy="-8.0178'
+b'567"\n     inkscape:document-units="px"\n     inkscape:current'
+b'-layer="layer1"\n     width="300px"\n     height="300px"\n     '
+b'showguides="true"\n     inkscape:guide-bbox="true"\n     inksc'
+b'ape:window-width="1430"\n     inkscape:window-height="817"\n  '
+b'   inkscape:window-x="0"\n     inkscape:window-y="27"\n     in'
+b'kscape:guide-points="true">\n    <sodipodi:guide\n       orien'
+b'tation="horizontal"\n       position="60"\n       id="guide373'
+b'1" />\n    <sodipodi:guide\n       orientation="vertical"\n    '
+b'   position="109"\n       id="guide2844" />\n  </sodipodi:name'
+b'dview>\n  <metadata\n     id="metadata7">\n    <rdf:RDF>\n      '
+b'<cc:Work\n         rdf:about="">\n        <dc:format>image/svg'
+b'+xml</dc:format>\n        <dc:type\n           rdf:resource="h'
+b'ttp://purl.org/dc/dcmitype/StillImage" />\n      </cc:Work>\n '
+b'   </rdf:RDF>\n  </metadata>\n  <g\n     inkscape:label="Layer '
+b'1"\n     inkscape:groupmode="layer"\n     id="layer1">\n    <re'
+b'ct\n       style="fill:#32b432;fill-opacity:1;stroke:#326432;'
+b'stroke-width:11.15463543;stroke-miterlimit:4;stroke-dasharra'
+b'y:none;stroke-opacity:1"\n       id="rect1872"\n       width="'
+b'195"\n       height="224"\n       x="53"\n       y="35" />\n    '
+b'<rect\n       style="fill:black;fill-opacity:1;stroke:none;st'
+b'roke-width:12;stroke-miterlimit:4;stroke-dasharray:none;stro'
+b'ke-opacity:1"\n       id="rect2760"\n       width="137.14285"\n'
+b'       height="128.57143"\n       x="86.857147"\n       y="111'
+b'.71679" />\n    <path\n       sodipodi:type="arc"\n       style'
+b'="opacity:1;fill:black;fill-opacity:1;stroke:#c8c8c8;stroke-'
+b'width:16;stroke-miterlimit:4;stroke-dasharray:none;stroke-da'
+b'shoffset:0;stroke-opacity:1"\n       id="path2836"\n       sod'
+b'ipodi:cx="190.5"\n       sodipodi:cy="208.5"\n       sodipodi:'
+b'rx="3.5"\n       sodipodi:ry="4.5"\n       d="M 194 208.5 A 3.'
+b'5 4.5 0 1 1  187,208.5 A 3.5 4.5 0 1 1  194 208.5 z"\n       '
+b'transform="translate(8,4)" />\n    <rect\n       style="opacit'
+b'y:1;fill:black;fill-opacity:1;stroke:#ffc837;stroke-width:12'
+b';stroke-miterlimit:4;stroke-dasharray:none;stroke-dashoffset'
+b':0;stroke-opacity:1"\n       id="rect2838"\n       width="63"\n'
+b'       height="5"\n       x="117"\n       y="157" />\n    <rect'
+b'\n       style="opacity:1;fill:black;fill-opacity:1;stroke:#f'
+b'fc837;stroke-width:12;stroke-miterlimit:4;stroke-dasharray:n'
+b'one;stroke-dashoffset:0;stroke-opacity:1"\n       id="rect284'
+b'0"\n       width="62"\n       height="6"\n       x="117"\n      '
+b' y="117.5" />\n    <rect\n       style="opacity:1;fill:black;f'
+b'ill-opacity:1;stroke:#ffc837;stroke-width:12;stroke-miterlim'
+b'it:4;stroke-dasharray:none;stroke-dashoffset:0;stroke-opacit'
+b'y:1"\n       id="rect2842"\n       width="64"\n       height="7'
+b'"\n       x="117"\n       y="82" />\n    <rect\n       style="op'
+b'acity:1;fill:black;fill-opacity:1;stroke:#ffc837;stroke-widt'
+b'h:12;stroke-miterlimit:4;stroke-dasharray:none;stroke-dashof'
+b'fset:0;stroke-opacity:1"\n       id="rect2850"\n       width="'
+b'65"\n       height="7"\n       x="117"\n       y="47.5" />\n  </'
+b'g>\n</svg>\n')
### end
